import { useState } from "react";
import type { FormEvent } from "react";
import { compareNeighbourhoods } from "../api/client";

export default function NeighbourhoodsPage() {
  const [areas, setAreas] = useState("Indiranagar, Bengaluru\nWhitefield, Bengaluru");
  const [workplace, setWorkplace] = useState("MG Road, Bengaluru");
  const [profile, setProfile] = useState("general"); const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { const candidate_areas = areas.split("\n").map(query => query.trim()).filter(Boolean).slice(0, 3).map(query => ({ query, label: query })); setData(await compareNeighbourhoods({ candidate_areas, workplace: { query: workplace, label: workplace }, profile, travel_mode: "DRIVE", period: "tomorrow" })); } catch (err) { setError(err instanceof Error ? err.message : "Comparison failed."); } finally { setLoading(false); } }
  return <main className="tool-page"><div className="page-intro"><h1>Neighbourhood comparison</h1><p>Compare up to three areas using air quality, forecast reliability, mobility, weather, and commute signals.</p></div><form className="tool-form" onSubmit={submit}><label>Candidate areas — one per line<textarea value={areas} onChange={e => setAreas(e.target.value)} rows={4} required /></label><label>Workplace<input value={workplace} onChange={e => setWorkplace(e.target.value)} required /></label><label>Household profile<select value={profile} onChange={e => setProfile(e.target.value)}><option value="general">General</option><option value="family_with_children">Family with children</option><option value="elderly_household">Elderly household</option><option value="outdoor_worker">Outdoor worker</option></select></label><button className="primary-button" disabled={loading}>{loading ? "Comparing…" : "Compare areas"}</button></form>{error && <p className="inline-error">{error}</p>}{data && <section className="results-list">{data.candidates.map((item: any, i: number) => <article className="result-card" key={item.candidate_label}><span className="result-card__rank">#{data.ranking?.indexOf(i) + 1 || "–"}</span><h2>{item.candidate_label}</h2><strong>{item.overall_score == null ? "Partial assessment" : `${Math.round(item.overall_score * 100)} / 100`}</strong><p>{item.air_quality_component?.explanation}</p><p>{item.commute_component?.explanation}</p>{item.limitations?.length > 0 && <small>{item.limitations.join(" ")}</small>}</article>)}</section>}</main>;
}
